### ISSUE TITLE
bugs While I am trying to run saveImgsAll()

### ISSUE THREAD

**Issue by Falmi** [lisjin/dcan-tensorflow#1]
It through this error can you help me to solve 
Subscript indices must either be real positive integers or logicals.

Error in fmArgmax (line 8)
topIndices(numImgs).ind = 0;

Error in saveImgsAll (line 7)
topIndices = fmArgmax(fmVals, imgNamesAll);

**Comment by lisjin** [comment]
It seems that the `numImgs` variable is assigned incorrectly. Try to debug line 6 of `fmArgmax` and figure out why it can't find the images.
