### ISSUE TITLE
object-level dice scores

### ISSUE THREAD

**Issue by dazhangyu123** [lisjin/dcan-tensorflow#10]
I want to know how to calculate the object-level dice loss

**Comment by lisjin** [comment]
You will need to implement the formula [here](https://warwick.ac.uk/fac/sci/dcs/research/tia/glascontest/evaluation/) for object-level dice loss. This project uses [Sørensen–Dice coefficient](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient), which is more efficient to compute.

**Comment by dazhangyu123** [comment]
I have solved this problem, thank you
