### ISSUE TITLE
The pixels of  contours

### ISSUE THREAD

**Issue by Bonsen** [lisjin/dcan-tensorflow#6]
```
    vals = unique(nonzeros(img));
    bwImg = false(size(img));
    for j = 1:length(vals)
        cur = (img == vals(j, 1));
        [bounds, ~] = bwboundaries(cur, 'noholes');
        indices = bounds{1};
        for k = 1:size(indices, 1)
            bwImg(indices(k, 1), indices(k, 2)) = 1;
        end
    end
    bwImg = imdilate(bwImg, strel('disk', 3));
    bwImg = uint8(bwImg) * 255;
    imwrite(bwImg, [OUT_DIR_C '/' imgNames{i}]);
```
I found the pixel size of contour is 6 when disk equals to 3, and it will cover pixels (==3) inside nucleis and outside nucleis (==3). And if contours are thick，the prediction covers more pixels inside the nucleis. What's more, if they are overlapped, the pixels outside this nucleis may cover some pixels inside other nucleis. It's hard to discriminate them.

Do I misunderstand?

**Comment by lisjin** [comment]
The radius of the contours is 3, not the diameter. If you disagree with any decisions I made, you are free to modify the code for your own purposes.
