### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: train.csv

### ISSUE THREAD

**Issue by imanrekh** [lisjin/dcan-tensorflow#9]
pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: train.csv
	 [[Node: ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TextLineReaderV2, input_producer)]]

**Comment by lisjin** [comment]
You can generate `train.csv` using this function: https://github.com/lisjin/dcan-tensorflow/blob/master/tf-dcan/bbbc006_input.py#L112
